// AUTO-GENERATED by scripts/generate-brownies.mjs — do not edit by hand.
// Regenerated on every `npm run dev` / `npm run build` from files in public/brownies/.

export type Brownie = {
  id: string;
  name: string;
  image: string;
};

export const BROWNIES: Brownie[] = [];
